import type { FileHandle, FileMetadata, HirayaClient } from "@hiraya-team/apps-sdk";
import { connectSystemApp, describeError, formatBytes, LatestOperation, required, setAppLoading } from "@hiraya/system-apps-shared";
import "./style.css";
type HirayaButton = HTMLElement & { disabled: boolean };
const APP_ID = "app.hiraya.file-viewer"; const status = required<HTMLElement>("#status"); const download = required<HirayaButton>("#download"); const operations = new LatestOperation(); const content = required<HTMLElement>("#content"); const details = required<HTMLElement>("#details"); const loading = required<HTMLElement>("#loading"); let downloadUrl: string | null = null; let hiraya: HirayaClient; let file: FileMetadata | null = null; let ready = false; let opening = false;
download.addEventListener("click", () => void saveCopy()); void start();
async function start() { try { const app = await connectSystemApp(APP_ID); hiraya = app.hiraya; ready = true; hiraya.on("commands.invoked", ({ id }) => { if (id === "open") void open(); }); app.onDispose(() => { operations.invalidate(); if (downloadUrl) URL.revokeObjectURL(downloadUrl); }); publishCommands(); if (app.launch.files[0]) await load(app.launch.files[0]); else { setAppLoading(content, details, loading); status.textContent = "Choose any file to inspect it."; } } catch (error) { setAppLoading(content, details, loading); fail(error, "File Viewer could not start."); } }
async function open() { const generation = operations.begin(); try { const selected = await hiraya.dialogs.openFile({ multiple: false }); if (selected?.[0] && operations.isLatest(generation)) await load(selected[0], generation); } catch (error) { if (operations.isLatest(generation)) fail(error, "Could not choose a file."); } finally { if (operations.isLatest(generation) && file) download.disabled = false; } }
async function load(handle: FileHandle, generation = operations.begin()) { opening = true; publishCommands(); setAppLoading(content, details, loading, "Opening file..."); download.disabled = true; try { const entry = await hiraya.files.stat(handle); if (!operations.isLatest(generation)) return; if (entry.kind !== "file") throw new Error("The selected item is not a file."); setAppLoading(content, details, loading, `Opening ${entry.metadata.name}...`); file = entry.metadata; required("#name").textContent = file.name; required("#type").textContent = file.mimeType; required("#size").textContent = formatBytes(file.size); required("#modified").textContent = new Date(file.modifiedAt).toLocaleString(); status.textContent = "File details ready. Content is read only when downloaded."; await hiraya.window.setTitle(`${file.name} - File Viewer`); } finally { if (operations.isLatest(generation)) { opening = false; setAppLoading(content, details, loading); download.disabled = !file; publishCommands(); } } }
async function saveCopy() { if (!file) return; const generation = operations.begin(); const selected = file; try { download.disabled = true; status.textContent = "Preparing download..."; const { data } = await hiraya.files.readAll(selected.handle); if (!operations.isLatest(generation)) return; if (downloadUrl) URL.revokeObjectURL(downloadUrl); downloadUrl = URL.createObjectURL(new Blob([data], { type: selected.mimeType })); const anchor = document.createElement("a"); anchor.href = downloadUrl; anchor.download = selected.name; anchor.click(); anchor.remove(); status.textContent = `Downloaded ${selected.name}.`; } catch (error) { if (operations.isLatest(generation)) fail(error, "Could not download the file."); } finally { if (operations.isLatest(generation)) download.disabled = false; } }
function fail(error: unknown, fallback: string) { status.textContent = describeError(error, fallback); status.classList.add("error"); }
function publishCommands() { void hiraya?.commands.set([{ id: "open", title: "Choose file", enabled: ready && !opening, promoted: true }]); }
