import type { FileHandle, FileMetadata, HirayaClient } from "@hiraya/apps-sdk";
import { connectSystemApp, describeError, DownloadUrlLease, formatBytes, LatestOperation, readFileData, required } from "@hiraya/system-apps-shared";
import "./style.css";
type HirayaButton = HTMLElement & { disabled: boolean };
const APP_ID = "app.hiraya.file-viewer"; const status = required<HTMLElement>("#status"); const openButton = required<HirayaButton>("#open"); const download = required<HirayaButton>("#download"); const operations = new LatestOperation(); const downloads = new DownloadUrlLease(); let hiraya: HirayaClient; let file: FileMetadata | null = null;
openButton.addEventListener("click", () => void open()); download.addEventListener("click", () => void saveCopy()); void start();
async function start() { try { const app = await connectSystemApp(APP_ID); hiraya = app.hiraya; app.onDispose(() => { operations.invalidate(); downloads.dispose(); }); openButton.disabled = false; if (app.launch.files[0]) await load(app.launch.files[0]); else status.textContent = "Choose any file to inspect it."; } catch (error) { fail(error, "File Viewer could not start."); } }
async function open() { const generation = operations.begin(); try { const selected = await hiraya.dialogs.openFile({ multiple: false }); if (selected?.[0] && operations.isLatest(generation)) await load(selected[0], generation); } catch (error) { if (operations.isLatest(generation)) fail(error, "Could not choose a file."); } finally { if (operations.isLatest(generation) && file) download.disabled = false; } }
async function load(handle: FileHandle, generation = operations.begin()) { const entry = await hiraya.files.stat(handle); if (!operations.isLatest(generation)) return; if (entry.kind !== "file") throw new Error("The selected item is not a file."); file = entry.metadata; required("#name").textContent = file.name; required("#type").textContent = file.mimeType; required("#size").textContent = formatBytes(file.size); required("#modified").textContent = new Date(file.modifiedAt).toLocaleString(); download.disabled = false; status.textContent = "File details ready. Content is read only when downloaded."; await hiraya.window.setTitle(`${file.name} - File Viewer`); }
async function saveCopy() { if (!file) return; const generation = operations.begin(); const selected = file; try { download.disabled = true; status.textContent = "Preparing download..."; const data = await readFileData(hiraya, selected.handle, selected.size); if (!operations.isLatest(generation)) return; downloads.download(data, selected.mimeType, selected.name); status.textContent = `Downloaded ${selected.name}.`; } catch (error) { if (operations.isLatest(generation)) fail(error, "Could not download the file."); } finally { if (operations.isLatest(generation)) download.disabled = false; } }
function fail(error: unknown, fallback: string) { status.textContent = describeError(error, fallback); status.classList.add("error"); }
