import type { FileHandle, FileMetadata, HirayaClient } from "@hiraya/apps-sdk";
import { connectSystemApp, describeError, downloadBuffer, formatBytes, readFileData, required } from "@hiraya/system-apps-shared";
import "./style.css";
const APP_ID = "app.hiraya.file-viewer"; const status = required<HTMLElement>("#status"); const download = required<HTMLButtonElement>("#download"); let hiraya: HirayaClient; let file: FileMetadata | null = null;
required("#open").addEventListener("click", () => void open()); download.addEventListener("click", () => void saveCopy()); void start();
async function start() { try { const app = await connectSystemApp(APP_ID); hiraya = app.hiraya; if (app.launch.files[0]) await load(app.launch.files[0]); else status.textContent = "Choose any file to inspect it."; } catch (error) { fail(error, "File Viewer could not start."); } }
async function open() { try { const selected = await hiraya.dialogs.openFile({ multiple: false }); if (selected?.[0]) await load(selected[0]); } catch (error) { fail(error, "Could not choose a file."); } }
async function load(handle: FileHandle) { const entry = await hiraya.files.stat(handle); if (entry.kind !== "file") throw new Error("The selected item is not a file."); file = entry.metadata; required("#name").textContent = file.name; required("#type").textContent = file.mimeType; required("#size").textContent = formatBytes(file.size); required("#modified").textContent = new Date(file.modifiedAt).toLocaleString(); download.disabled = false; status.textContent = "File details ready. Content is read only when downloaded."; await hiraya.window.setTitle(`${file.name} - File Viewer`); }
async function saveCopy() { if (!file) return; try { download.disabled = true; status.textContent = "Preparing download..."; const data = await readFileData(hiraya, file.handle, file.size); downloadBuffer(data, file.mimeType, file.name); status.textContent = `Downloaded ${file.name}.`; } catch (error) { fail(error, "Could not download the file."); } finally { download.disabled = false; } }
function fail(error: unknown, fallback: string) { status.textContent = describeError(error, fallback); status.classList.add("error"); }
